/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PharmaAdminRole;

import NewLifeCenter.NewLife;
import NewLife.WorkList.PharmacyInventory;
import NewLife.Porter.PorterDirectory;
import NewLife.UserAccount.UserAccount;
import NewLife.WorkList.LabWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shivaniguglani
 */
public class AcceptOrRejectOrder extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount userAccount;
    NewLife newLife;
    LabWorkRequest labTestWorkRequest;
    double total = 0.0;
    private DefaultTableModel defaultTableModel;
    private PorterDirectory deliveryManDirectory;
    private List<PharmacyInventory> itemQuantityList = new ArrayList<>();
    private int index = -1;
    public AcceptOrRejectOrder(JPanel userProcessContainer, NewLife newLife, UserAccount userAccount, LabWorkRequest labTestWorkRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.newLife = newLife;
        this.userAccount = userAccount;
        this.labTestWorkRequest = labTestWorkRequest;
        defaultTableModel = (DefaultTableModel) tblOrderDetails.getModel();
        deliveryManDirectory = newLife.getDeliveryManDirectory();   
        change();
        display();
    }
    
    
    // to display
    private void display() {
                
        pharmaName.setText(labTestWorkRequest.getPharmacy().getPharmacyName());
        status.setText(labTestWorkRequest.getStatus());
        message.setText(labTestWorkRequest.getMessage());

        defaultTableModel.setRowCount(0);
        for (PharmacyInventory itemWithQuantity : labTestWorkRequest.getPharmaItemQuantitys()) {
            Object[] row = new Object[defaultTableModel.getColumnCount()];
            row[0] = itemWithQuantity;
            row[1] = itemWithQuantity.getQuantity();
            row[2] = itemWithQuantity.getMedicines().getMedicinePrice() * itemWithQuantity.getQuantity();
            total += itemWithQuantity.getMedicines().getMedicinePrice() * itemWithQuantity.getQuantity();
            defaultTableModel.addRow(row);
        }
        totalPrice.setText(total + "");

    }
    
    private void declineOrder(){
        labTestWorkRequest.setStatus("Declined");
        JOptionPane.showMessageDialog(null, "Order has been declined");
        change();
        status.setText(labTestWorkRequest.getStatus());
    }
    
    private void change() {
        switch(labTestWorkRequest.getStatus()){
            case "Request to Pharmaceutical": {
                acceptOrder.setText("Accept order");
                declineOrder.setVisible(true);
            }
            case "Preparing": {
                acceptOrder.setText("Ready for delivery");
                declineOrder.setVisible(false);
            }
            default: {
                declineOrder.setVisible(false);
                acceptOrder.setVisible(false);
            }
        }
        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartScrollPane1 = new javax.swing.JScrollPane();
        tblOrderDetails = new javax.swing.JTable();
        lblPharmaName = new javax.swing.JLabel();
        pharmaName = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblOrderTotal = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        acceptOrder = new javax.swing.JButton();
        declineOrder = new javax.swing.JButton();
        lblBackButton = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        cartScrollPane1.setForeground(new java.awt.Color(255, 153, 51));

        tblOrderDetails.setBackground(new java.awt.Color(204, 255, 204));
        tblOrderDetails.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        tblOrderDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM NAME", "ITEM QUANTITY", "ITEM PRICE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartScrollPane1.setViewportView(tblOrderDetails);

        lblPharmaName.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        lblPharmaName.setForeground(new java.awt.Color(255, 255, 255));
        lblPharmaName.setText("Pharmacy Name");

        pharmaName.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        pharmaName.setForeground(new java.awt.Color(255, 255, 255));
        pharmaName.setText("<value>");

        status.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setText("<value>");

        lblStatus.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("Status");

        lblOrderTotal.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        lblOrderTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderTotal.setText("Total");

        totalPrice.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        totalPrice.setForeground(new java.awt.Color(255, 255, 255));
        totalPrice.setText("<value>");

        message.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        message.setForeground(new java.awt.Color(255, 255, 255));
        message.setText("<value>");

        lblMessage.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage.setText("Message");

        acceptOrder.setBackground(new java.awt.Color(255, 255, 204));
        acceptOrder.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        acceptOrder.setText("Accept Order");
        acceptOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptOrderActionPerformed(evt);
            }
        });

        declineOrder.setBackground(new java.awt.Color(255, 255, 204));
        declineOrder.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        declineOrder.setText("Decline Order");
        declineOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                declineOrderMousePressed(evt);
            }
        });
        declineOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineOrderActionPerformed(evt);
            }
        });

        lblBackButton.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        lblBackButton.setForeground(new java.awt.Color(255, 255, 255));
        lblBackButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackButton.setText("ORDER DETAILS");

        btnBack1.setBackground(new java.awt.Color(255, 255, 204));
        btnBack1.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/PharmaAdminRole/package.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(lblOrderTotal)
                                .addGap(73, 73, 73)
                                .addComponent(totalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(lblStatus)
                                    .addGap(73, 73, 73)
                                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPharmaName)
                                    .addGap(61, 61, 61)
                                    .addComponent(pharmaName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lblMessage)
                                .addGap(59, 59, 59)
                                .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cartScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(acceptOrder)
                        .addGap(42, 42, 42)
                        .addComponent(declineOrder)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnBack1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack1)
                .addGap(58, 58, 58)
                .addComponent(lblBackButton)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cartScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPharmaName)
                            .addComponent(pharmaName)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStatus)
                                    .addComponent(status))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrderTotal)
                                    .addComponent(totalPrice))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMessage)
                                    .addComponent(message))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(declineOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acceptOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(167, 167, 167))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceptOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptOrderActionPerformed

        if (labTestWorkRequest.getStatus().equals("Request to Pharmaceutical")) {
            labTestWorkRequest.setStatus("Preparing");
            JOptionPane.showMessageDialog(null, " Order Accepted");
        }
        else if(labTestWorkRequest.getStatus().equals("Preparing")) {
            labTestWorkRequest.setStatus("Prepared for Pharmacy");
            labTestWorkRequest.setMessage("Order List :"+labTestWorkRequest.getPharmaItemQuantitys().toString());
            JOptionPane.showMessageDialog(null, " Order sent to Pharmacy");
        }
        else {
            acceptOrder.setVisible(false);
        }
        change();
        status.setText(labTestWorkRequest.getStatus());

    }//GEN-LAST:event_acceptOrderActionPerformed

    private void declineOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_declineOrderMousePressed
        declineOrder();
    }//GEN-LAST:event_declineOrderMousePressed

    private void declineOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_declineOrderActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        ViewOrderInformation viewOrderDetails = new ViewOrderInformation(userProcessContainer,newLife, userAccount);
        userProcessContainer.add("ViewOrderDetails", viewOrderDetails);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptOrder;
    private javax.swing.JButton btnBack1;
    private javax.swing.JScrollPane cartScrollPane1;
    private javax.swing.JButton declineOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBackButton;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblOrderTotal;
    private javax.swing.JLabel lblPharmaName;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel message;
    private javax.swing.JLabel pharmaName;
    private javax.swing.JLabel status;
    private javax.swing.JTable tblOrderDetails;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
